[project]
name = "khrapovs.github.io"
version = "0.1.0"
description = "Profile page of Stansislav Khrapov"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mkdocs-landing>=0.0.6", "mkdocs>=1.6.1"]
