name: Publish docs

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: uv sync

    - name: Build docs
      run: uv run mkdocs build

    - name: Commit
      run: |
        git add --all
        git config --global user.email "khrapovs@gmail.com"
        git config --global user.name "Stanislav Khrapov"
        git commit --all -m "sys: Build documentation"
    
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
